.editorconfig, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/other.md, .github/dependatbot.yml, .github/release-draft-template.yml, .github/workflows/test.yml, .gitignore, README.md, bors.toml, firebase.json, functions/.eslintrc.js, functions/.gitignore, functions/package-lock.json, functions/package.json, functions/src/index.ts, functions/tsconfig.dev.json, functions/tsconfig.json, package.json
=> Create chore of the project

.github/workflows/release-drafter.yml
=> Add release drafter

CONTRIBUTING.md, bors.toml
=> Improve contributing and add Bors all version test

.github/scripts/check-release.sh, .github/workflows/publish.yml, CONTRIBUTING.md, functions/lib/adapter.js, functions/lib/config.js, functions/lib/import/config.js, functions/lib/import/index.js, functions/lib/index.js, functions/lib/logs.js, functions/lib/util.js, functions/lib/version.js, functions/src/version.ts, script/version.sh
=> Add publish in the github action CI

functions/__tests__/adapter.test.ts, functions/lib/adapter.js, functions/package.json, functions/src/adapter.ts, functions/yarn.lock
Reverts meilisearch/firestore-meilisearch#46
=> Revert upgrade of firebase-admin package

CHANGELOG.md
Add v0.1.3 to the `CHANGELOG.md`
=> Update the changelog file

CONTRIBUTING.md
=> Add changelog modif step on contributing

README.md
We should add this section in order to run the pre-release script :)
=> Add Compatibility with Meilisearch section

PREINSTALL.md, README.md
=> Fix typo in README

README.md
The link to the import script is broken
=> Fix import script link

extension.yaml
=> Improve placeholders

functions/jest.config.js
=> Remove unecessary warning during tests

.github/workflows/publish.yml, CONTRIBUTING.md
=> Add publishing on firestore in publish CI

CHANGELOG.md
=> Add changelog for 0.1.4

functions/package.json, functions/yarn.lock
Update meilisearch-js to latest none-beta version
=> Update meilisearch-js to v0.27.0

CHANGELOG.md
Update the changelog files for the next release
=> Update changelog of v0.1.5 changes

extension.yaml
=> Change description of displayName to be less than 40 chars

extension.yaml
fixes: #109
Fixes #<issue_number>
=> Convert Meilisearch API key param to secret type

PREINSTALL.md, README.md
=> Update README to reference Meilisearch cloud

functions/__tests__/functions.test.ts, functions/lib/index.js, functions/lib/validate.js, functions/src/index.ts, functions/src/logs.ts, functions/src/validate.ts, functions/yarn.lock
fixes: #104
In this PR we are checking if the document id of an entry is well formatted based on [Meilisearch requirements](https://docs.meilisearch.com/learn/core_concepts/primary_key.html#formatting-the-document-id). 
It also includes some changes on the logs, in order to log the document_id error we added, but also to avoid showing an entry contained in the logs. For security reasons but also to avoid logs being too big.
=> Validate document id formating

functions/lib/index.js, functions/lib/logs.js, functions/lib/validate.js, functions/src/logs.ts, functions/src/validate.ts
Fixes some errors in the js-doc comments. Outdated parameters definition and bad wording
=> Update js-docs with accurate information

functions/lib/index.js
A build file was not builded correctly. Fixing this here
=> Update outdated build files

extension.yaml, functions/lib/index.js, functions/lib/version.js, functions/package.json, functions/src/version.ts, functions/yarn.lock, package.json
=> Update version for the next release (v0.1.6)

CHANGELOG.md, extension.yaml, functions/lib/version.js, functions/package.json, functions/src/version.ts, functions/yarn.lock, package.json
=> Update version for the next release (v0.1.7)

CHANGELOG.md, extension.yaml, functions/lib/version.js, functions/package.json, functions/src/version.ts, package.json
Update version to v0.1.9 to apply CI changes on publishing
=> Update version for the next release (v0.1.9)

PREINSTALL.md, README.md
Fixes #130 
- Replaces the old URL `https://console.firebase.google.com/project/_/extensions/install?ref=meilisearch/firestore-meilisearch` with `https://extensions.dev/extensions/meilisearch/firestore-meilisearch`
- There are also some formatting changes to make the Readme look nicer. Hope they won't be a problem. 
- [ Yes] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [Yes ] Have you read the contributing guidelines?
- [Yes ] Have you made sure that the title is accurate and descriptive of the changes?
=> replaced the old URL and checked other files for its presence 

PREINSTALL.md, README.md
Fixes #131
— this if for fixing geoSearch link in the documentation because the link was not appearing well
=> fix geoSearch link

extension.yaml
Fixes #138 
- Updates the display name for the extension.
=> Updates the display name for the extension in the marketplace

CHANGELOG.md, extension.yaml, functions/lib/import/config.js, functions/lib/import/index.js, functions/lib/index.js, functions/lib/version.js, functions/package.json, functions/src/version.ts, functions/yarn.lock, package.json
=> Update version for the next release (v0.1.10)

extension.yaml, functions/lib/version.js, functions/package.json, functions/src/version.ts, package.json
This version makes this package compatible with Meilisearch v0.30.0 :tada:
Check out the changelog of [Meilisearch v0.30.0](https://github.com/meilisearch/meilisearch/releases/tag/v0.30.0) for more information on the changes.
=> Update version for the next release (v0.1.11)

CHANGELOG.md
Adds a changelog for the changes introduced in v0.1.12 of the plugin
=> Add changelog for version v0.1.12

.github/workflows/beta-tests.yml, .github/workflows/pre-release-tests.yml, .github/workflows/publish.yml, .github/workflows/test.yml, CONTRIBUTING.md, bors.toml, extension.yaml, functions/package.json
Fixes https://github.com/meilisearch/firestore-meilisearch/issues/178
=> Update nodejs runtime to node20

CHANGELOG.md, extension.yaml
Required for deploying the extension
=> Add v0.3.0 changelog

CHANGELOG.md, extension.yaml, functions/lib/version.js, functions/package.json, functions/src/version.ts, package-lock.json, package.json
Cannot republish `0.3.0` to Firebase, we need to update to the version
- Update version to v0.3.1
- Rebuild
=> Bump to v0.3.1
